auth:
  build: .
  command: 'bash -c ''bundle exec rake db:setup && /sbin/my_init'''
  environment: 
    RAILS_ENV: development
    RACK_ENV: development
    WSGI_ENV: development
    NODE_ENV: development
    PASSENGER_APP_ENV: development
  working_dir: /app/user/
  ports:
    - '3000:80'
  links:
    - postgres
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: password
  ports:
    - "5432"