auth:
  image: kibiluzbad/gozer_auth
  cpu_shares: 84
  mem_limit: 199000000
  working_dir: /app/user/
  volumes:
    - "/app/user:/home/leonardo/work/gozer/auth"
  environment: 
    RAILS_ENV: development
    RACK_ENV: development
    WSGI_ENV: development
    NODE_ENV: development
    PASSENGER_APP_ENV: development
  ports:
    - "3000:80"
  links:
    - postgres
postgres:
  image: postgres
  cpu_shares: 100
  mem_limit: 199000000
  environment:
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"