source 'https://rubygems.org'

ruby '2.3.1'

gem 'backburner'
gem 'rest-client'
gem 'usagewatch'
gem 'system'
gem 'sys-filesystem'
gem 'mac-address'
gem 'sys-proctable'

group :test, :development do
  gem 'rspec', '~> 3.4.0'
  gem 'nyan-cat-formatter', '~> 0.11'
  gem 'guard', '~>2.13.0'
  gem 'guard-rspec', '~>4.6.5'
  gem 'pry', '~>0.10.3'
end
