FROM ruby:2.3.1

MAINTAINER Leonardo Cardoso <kibiluzbad@gmail.com>

ENV PORT 9292
# Create some needed directories
RUN mkdir -p /app/user
WORKDIR /app/user

RUN gem install bundler
ADD . /app/user/
RUN bundle install

EXPOSE 9292:9292

CMD ["bundle","exec","puma"]