source 'https://rubygems.org'

ruby '2.3.1'

gem 'puma'
gem 'faye-websocket'
gem 'sinatra', '~> 1.4.7git'
gem 'shotgun', '~> 0.9.1'

gem 'httparty'
gem 'oauth2'
gem 'em-websocket'
gem 'rethinkdb'
gem 'sinatra-cross_origin', '~> 0.3.1'

group :test, :development do
  gem 'rspec', '~> 3.4.0'
  gem 'nyan-cat-formatter', '~> 0.11'
  gem 'guard', '~>2.13.0'
  gem 'guard-rspec', '~>4.6.5'
  gem 'pry', '~>0.10.3'
end